### ISSUE TITLE
No need to keep the drawing object

### ISSUE THREAD

**Issue by cnjinhao** [JamesBremner/nanaplot#1]
It is not needed to keep the instance of `drawing`.
https://github.com/JamesBremner/nanaplot/blob/3e9c58c41e18d6962bc3650f7810951b36317854/plot.cpp#L13-L15

Just define a local variable
```
drawing( parent ).draw([this](paint::graphics& graph) 
{ 
});
```
When the `drawing` object gets destroyed, the drawer functions are still alive. Because the `drawing` doesn't manage the life-time of drawer functions, it is just for installing drawer functions.

**Comment by JamesBremner** [comment]
@cnjinhao Thanks for looking so carefully at this code.
